apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: add-static-route
spec:
  selector:
    matchLabels:
      name: add-static-route
  template:
    metadata:
      labels:
        name: add-static-route
    spec:
      hostNetwork: true
      containers:
        - name: add-static-route
          image: ibmcase/kubectl
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c" ]
          args:
          - >
              _gateway="192.168.140.247 dev eth0";
              echo "172.21.0.0/16" > routes.txt;
              echo "172.22.0.0/16" >> routes.txt;
              echo "172.23.0.0/16" >> routes.txt;
              while true;
              do
                for _route in `cat routes.txt | awk '{print $1;}'`; do
                  [ -z "`ip route show | grep ${_route} | grep ${_gateway}`" ] || continue;
                  echo "Adding ${_route} via ${_gateway} ...";
                  ip route add ${_route} via ${_gateway};
                done;
                sleep 60;
              done;
          securityContext:
            capabilities:
              add:
              - NET_ADMIN