apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: "2.6.3"
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
      interval: 5m
  values:
    tls: external
    hostname: rancher.ingtra.net
    addLocal: "false"